# Server
server.port=8080
server.thread-pool-size=10
server.max-request-size=10485760
server.max-response-size=10485760
server.static-files-path=static/

# Database
db.host=localhost
db.port=15432
db.name=server_db
db.username=server_user
db.password=server_pass
db.pool.size=5