services:
  postgres:
    image: postgres
    container_name: pg-server-rest-api
    restart: always
    environment:
      POSTGRES_USER: server_user
      POSTGRES_PASSWORD: server_pass
      POSTGRES_DB: server_db
    ports:
      - "15432:5432"
    volumes:
      - data:/var/lib/postgresql

volumes:
  data: